### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by malb** [malb/cysignals#3]
Is signal.pyx a good name? What about `signal_pyx` and `signals` for the modules?

**Comment by malb** [comment]
Okay, perhaps it should be `signals.pyx` for consistency (`signal` is already a built-in module)

**Comment by jdemeyer** [comment]
> signal.pyx

Generally, I'm not fond of special characters in software names: it would need to be renamed anyway for Sage inclusion (like `path.py` which is `pathpy` in Sage). Also, the name `signal(s).pyx` seems to imply that it's just one file.

On the `sage-devel` thread, I proposed `cysignals` and other people proposed `cygnals` (which I personally don't like very much).

**Comment by kiwifb** [comment]
`signal.pyx` won't get you many friends on the packaging side. We'd rather keep `.` as a separator for other things. I can see the appeal of `cygnals` but you always regret that kind of puns in the long run. `cysignals` is clear and explicit and has my vote.

**Comment by vbraun** [comment]
How about `sage.interrupt` namespace package?

**Comment by vbraun** [comment]
`cython_signals` or `Cython_Signals`? (Cython uses camelcase)

**Comment by jdemeyer** [comment]
In decreasing order of preference:

1. `cysignals`
2. `cython_signals`
3. `Cython_Signals`
4. `cygnals`
5. `signals.pyx`
6. `sage.interrupt`

**Comment by malb** [comment]
`cysignals` seems to match the naming convention closest: https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by malb** [comment]
I'll change everything over to `cysignals` in, say, 2-3 hours. Naming discussions can drag on forever and there seems to be no opposition to it (?)

**Comment by jdemeyer** [comment]
I would at least let @vbraun react. Then hopefully he can take care of #5 too.

**Comment by vbraun** [comment]
cysignals is fine with me...
