### ISSUE TITLE
Move under umbrella of sagemath organisation on GitHub

### ISSUE THREAD

**Issue by malb** [malb/cysignals#5]
This code shouldn't live under @malb, but under @sagemath.

**Comment by jdemeyer** [comment]
@vbraun: you have write access to @sagemath, right?

**Comment by vbraun** [comment]
Yes, I should be able to do it. Ideally we settle on the name first ;-)

**Comment by jdemeyer** [comment]
`cysignals`?

**Comment by vbraun** [comment]
Unless you want to keep this fork, can you make me admin so I can move the repo to sagemath

**Comment by malb** [comment]
So I'd transfer ownership to you and you would then transfer it to sagemath (after we renamed it)?

**Comment by vbraun** [comment]
Yes, that should work
